name: Build Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
    - uses: actions/cache@v6.1.0
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Generate zip
      uses: 10up/action-wordpress-plugin-build-zip@1.0.2
      env:
        SLUG: edge-woocommerce # optional, remove if GitHub repo name matches SVN slug, including capitalization
