name: Release

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v7.0.1
            - uses: actions/cache@v6.1.0
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Setup PHP
              uses: shivammathur/setup-php@2.37.2
              with:
                  php-version: '8.5.9'
                  tools: composer
            - name: Setup Node.js
              uses: actions/setup-node@v7.0.0
              with:
                  node-version: '26.1.0'
            - name: Install Composer dependencies
              run: composer install --no-dev --optimize-autoloader
            - name: Install npm dependencies
              run: npm install
            - name: Build blocks and assets
              continue-on-error: true
              run: npm run build
            - name: Build a plugin zip
              run: npm run plugin-zip
            - name: Upload release asset
              uses: softprops/action-gh-release@v3.0.3
              env:
                  # Note, this is an exception to action secrets: GH_TOKEN is always available and provides access to
                  # the current repository this action runs in.
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  # Provide what the file should be named when attached to the release (plugin-name.zip)
                  files: ${{ github.workspace }}/woocommerce-edge-gateway.zip
